### PR TITLE
fix(multer-sharp): fix for sharpjs for samsung galaxy images

### PR DESCRIPTION
**Pull request by dineshsalunke**
SharpJs crashes on trying to work on Images taken from Samsung devices.

Refer to below issue
https://github.com/lovell/sharp/issues/1880

### CODE REVIEW

**Comment by jeffminsungkim** [comment]
Thanks for the PR @dineshsalunke 
Why the curly braces were added? Prettier should remove them automatically when you save.
I should migrate tslint from eslint as soon as I can. (not that difficult)

**Comment by dineshsalunke** [comment]
hey,

the braces were added due my tslint config ( which again happens on save :( ) I would suggest we add a git hooky which run prettier to clean it up

**Comment by jeffminsungkim** [comment]
Actually, we already have a pre-commit hook.
You should run `npm run commit` then the lint-staged will run the pretty-quick for you.

**Comment by dineshsalunke** [comment]
actually that's npm script what i am using to commit

**Comment by jeffminsungkim** [comment]
Hmm.. that's weird. The thing is, you have to fix the syntax though. 😢

**Pull request merged**
