### PR TITLE
feat(config): allow to pass all config options for AWS and S3 instances

### LINKED ISSUE #170: Make access keys optional?
Would like to leverage IAM roles in production: https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-iam.html

In development, it might also make sense to not use explicit keys and instead use the local configuration in `~/.aws`.

### PR DESCRIPTION
**Pull request by visurel**
Fixes #170 

Let me know if there's anything to adjust, I'd love to get this in, so we can pass all config options or none at all to the AWS/S3 Instances.

### CODE REVIEW

**Comment by jeffminsungkim** [comment]
Great job @visurel and Thank you :)
Looks good to me!
Could you please also update the readme file?

**Comment by visurel** [comment]
@jeffminsungkim Thanks! Added the requested changes. :)

**Review by jeffminsungkim — APPROVED** [review]
Thank you 👍

**Comment by jeffminsungkim** [comment]
@all-contributors please add @visurel  for code, doc

**Pull request merged**
